### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by davisdude** [Shell64/GunigineAudio#1]
First I want to start by saying that this library looks really promising!
However, without proper documentation it will be much harder to use... 
This is not extremely pressing, but it is fairly important.

Thanks again

**Comment by Shell64** [comment]
Hello, I feel worried about documentation because it follows exactly how love.audio works (and how it's described in their wiki). The things that doesnt work is because this library is missing, and it's under development. But you are probably wanting to know about how to include the library in your project or about using audio effects.

**Comment by davisdude** [comment]
I was not aware that it was still under development, my bad... 
However, LOVE does not include things like filters, etc. But I understand that this will come later

**Comment by Shell64** [comment]
Yes the example creation and usage is in the example file. The parameters for now you can get from OpenAL wrap for example https://github.com/Shell64/GunigineAudio/blob/master/GunigineAudio/Internal/Abstraction/Audio/AL/AL.lua#L596
it describes "AL_EAXREVERB_MIN_DENSITY", this means.. theres a effect that is called "eaxreverb" and it does have a param called "min_density" that can be set.

**Comment by Shell64** [comment]
In this block of code https://github.com/Shell64/GunigineAudio/blob/master/GunigineAudio/Internal/Abstraction/Audio/AL/AL.lua#L384
it shows which ones are filters and which ones are effects, "AL_FILTER_LOWPASS" means that "lowpass" is a filter and can be used in newFilter("lowpass") .
